name: Pages

on:
  schedule:
    - cron: '0 14 * * *' # JST 23:00
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm i

      - name: Run pipeline (generate public/)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ARXIV_QUERY: ${{ secrets.ARXIV_QUERY }}
          ARXIV_MAX: ${{ secrets.ARXIV_MAX || 1 }}
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL || format('https://{0}.github.io/{1}', github.repository_owner, github.event.repository.name) }}
        run: npm start

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
